# Generated by Django 6.1.1 on 2026-09-16 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_delivery_cost_alter_order_status'),
        ('payments', '0003_payment_provider_order_reference_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_payment_provider_reference',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_provider_reference_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_order_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=45),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SUCCESSFUL')), fields=('order',), name='unique_successful_payment_per_order'),
        ),
    ]
