# Generated by Django 6.1.1 on 2026-09-28 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('products', '0014_producttype_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCartSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guest', models.BooleanField()),
                ('cart_created_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('abandoned_at', models.DateTimeField(db_index=True)),
                ('recovered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('items_count', models.PositiveIntegerField()),
                ('value_uah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_uah_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_usd_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_snapshots', to='carts.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_cart_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='AbandonedCartSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('2XS', '2XS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('price_uah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abandoned_cart_items', to='products.product')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.abandonedcartsnapshot')),
            ],
        ),
    ]
