# Generated by Django 6.1.1 on 2026-09-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_size'),
        ('orders', '0004_remove_order_delivery_cost_alter_order_status'),
    ]

    operations = [
    ]
