apiVersion: 1
groups:
    - orgId: 1
      name: prod-backups
      folder: brand-clothing
      interval: 10m
      rules:
        - uid: bfzzeuyy4ipz4d
          title: prod backup failed
          condition: C
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: grafanacloud-logs
              model:
                datasource:
                    type: loki
                    uid: grafanacloud-logs
                editorMode: code
                expr: count_over_time({env="prod", container="db"} |= "WAL-G backup FAILED" [1h])
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          isPaused: false
          notification_settings:
            receiver: grafana-maxmlv-email
        - uid: bfzzf098sjlkwc
          title: prod WAL archiving failing
          condition: C
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: grafanacloud-logs
              model:
                datasource:
                    type: loki
                    uid: grafanacloud-logs
                editorMode: code
                expr: count_over_time({env="prod", container="db"} |= "archive command failed" [15m])
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 10m
          isPaused: false
          notification_settings:
            receiver: grafana-maxmlv-email
        - uid: afzzf81vtv11ce
          title: prod backup missing (26h)
          condition: C
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: grafanacloud-logs
              model:
                datasource:
                    type: loki
                    uid: grafanacloud-logs
                editorMode: code
                expr: count_over_time({env="prod", container="db"} |= "WAL-G backup completed" [26h])
                hide: false
                instant: true
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: Alerting
          execErrState: Error
          for: 10m
          isPaused: true
          notification_settings:
            receiver: grafana-maxmlv-email
    - orgId: 1
      name: prod-infra
      folder: brand-clothing
      interval: 1m
      rules:
        - uid: cfzx8315d7w8we
          title: prod disk above 85%
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: grafanacloud-prom
              model:
                editorMode: code
                expr: 100 * (1 - node_filesystem_avail_bytes{env="prod", mountpoint=~"/|/data"} / node_filesystem_size_bytes{env="prod", mountpoint=~"/|/data"})
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 85
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 10m
          isPaused: false
          notification_settings:
            receiver: grafana-maxmlv-email
        - uid: ffzx88245wa2oe
          title: prod memory available below 10%
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: grafanacloud-prom
              model:
                editorMode: code
                expr: 100 * node_memory_MemAvailable_bytes{env="prod"} / node_memory_MemTotal_bytes{env="prod"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 10m
          isPaused: false
          notification_settings:
            receiver: grafana-maxmlv-email
        - uid: afzx8c40udm9sc
          title: prod not sending metrics
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: grafanacloud-prom
              model:
                editorMode: code
                expr: absent_over_time(up{env="prod"}[10m])
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              queryType: expression
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 5m
          isPaused: false
          notification_settings:
            receiver: grafana-maxmlv-email
