# Generated by Django 6.1.1 on 2026-09-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
