# Generated by Django 6.1.1 on 2026-09-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productimage_color_remove_productcolor_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fabric',
        ),
    ]
