# Generated by Django 6.1.1 on 2026-09-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_availabilityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(default='dress', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
