# Generated by Django 6.1.1 on 2026-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_producttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='collections/'),
        ),
    ]
